### ISSUE TITLE
Create YAML outputs for...

### ISSUE THREAD

**Issue by elacosse** [elacosse/metamersion-latent#6]
1. From chat history 

2. From analysis 

3. Exit Conversation

**Comment by lunarring** [comment]
we wanna make a folder, structure DATE_TIME_SUBJECT -> 230123_1520_Johannes

feel free using this
def get_time(resolution=None):
    if resolution==None:
        resolution="second"
    if resolution == "day":
        t = time.strftime('%y%m%d', time.localtime()) 
    elif resolution == "minute":
        t = time.strftime('%y%m%d_%H%M', time.localtime())
    elif resolution == "second": 
        t = time.strftime('%y%m%d_%H%M%S', time.localtime())
    elif resolution == "millisecond":
        t = time.strftime('%y%m%d_%H%M%S', time.localtime())
        t += "_"
        t += str("{:03d}".format(int(int(datetime.utcnow().strftime('%f'))/1000)))
    else:
        raise ValueError("bad resolution provided: %s" %resolution)
    return t

foldername = f"{get_time('second')}_{subj}"

**Comment by lunarring** [comment]
also could 1. be a function call from chat? e.g. close_chat_write_yaml() or so? and who should call it? maybe the chat obj itself, after it injected it's last summary statement?
