### ISSUE TITLE
Update run_chat.py with latent_blending images to concatenate for card.

### ISSUE THREAD

**Issue by elacosse** [elacosse/metamersion-latent#8]

**Comment by lunarring** [comment]
negative_prompt = "ugly, blurry"  
#negative_prompt = ""  

seed = 420
width = 768
height = 512

ip_server = "138.2.229.216"
zmq_client = Client(ip_server, 7555, 7556, image_dims=IMAGE_DIMS, verbose=True)

# don't change below
from tqdm import tqdm
list_imgs = []
for prompt in tqdm(prompts):
  dict_meta = {}
  dict_meta['prompt'] = prompt
  dict_meta['neg_prompt'] = negative_prompt
  dict_meta['seed'] = seed
  dict_meta['width'] = width
  dict_meta['height'] = height
  img = zmq_client.run_image(dict_meta)
  list_imgs.append(img)
